name: report
repository: github.com/danhnguyen2201/trivy-plugin-report
version: "0.1.0
output: true
summary: A trivy plugin that can convert scan results into excel
usage: Template
description: |-
  A trivy plugin that can convert scan results into excel
platforms:
  - selector:
      os: linux
      arch: amd64
    uri: ./trivy-plugin-report
    bin: ./trivy-plugin-report
